### PR TITLE
Adding Missing Dependencies and Fixing Code Formatting

### PR DESCRIPTION
**Pull request by kwirkykat**
I added the missing dependencies on xPSDesiredStateConfiguration and xWebAdministration. This should fix the DSC Resource not showing up on the PowerShell Gallery.

I also fixed some of the code formatting to fit with the DSC Resource style guidelines.

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xphp/4)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Pester is failing because these modules aren't currently dependencies in the PowerShell Gallery. This PR should fix that after the next release.

**Comment by TravisEz13** [comment]
:lgtm:  Will leave open for comments for some time.

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xphp/4#-:-KGPEJDaFsevxV_9h6TS:-965675503)_

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[xPhp.psd1, line 50 [r2]](https://reviewable.io:443/reviews/powershell/xphp/4#-KGPEpdkbtn5Z0n30N1z:-KGPEpdl0F38DUBJTaVI:-557152905) ([raw file](https://github.com/powershell/xphp/blob/0a08eaedc7a4b8c5dd92c34c8001da9ac7862320/xPhp.psd1#L50)):_
Apparently other than a test failure, this makes these required to test the module, so you must update the tests / or appveyor.yml to install the modules.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xphp/4)_

**Comment by kwirkykat** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[xPhp.psd1, line 50 [r2]](https://reviewable.io:443/reviews/powershell/xphp/4#-KGPEpdkbtn5Z0n30N1z:-KGwVL86zOkCpb-7K1OB:-499146009) ([raw file](https://github.com/powershell/xphp/blob/0a08eaedc7a4b8c5dd92c34c8001da9ac7862320/xPhp.psd1#L50)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xphp/4)_

**Comment by TravisEz13** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xphp/4)_

**Pull request merged**
